version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"